# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloLiveGQL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloLiveGQL
  pod 'LiveGQL', '~> 2.0.0'

end
